surface_set_target(Battle_GetBoardSurface());
draw_sprite_ext(spr_pixel,0,_frame_up_x,_frame_up_y,_frame_up_width,_frame_up_height,_angle,battle_board.color_frame,battle_board.alpha_frame);
draw_sprite_ext(spr_pixel,0,_frame_left_x,_frame_left_y,_frame_left_width,_frame_left_height,_angle,battle_board.color_frame,battle_board.alpha_frame);
draw_sprite_ext(spr_pixel,0,_frame_down_x,_frame_down_y,_frame_down_width,_frame_down_height,_angle,battle_board.color_frame,battle_board.alpha_frame);
draw_sprite_ext(spr_pixel,0,_frame_right_x,_frame_right_y,_frame_right_width,_frame_right_height,_angle,battle_board.color_frame,battle_board.alpha_frame);
surface_reset_target();